services:
  templatesrv:
    environment:
      - GRACEFUL_SHUTDOWN_PRESTOP_TIMEOUT_SEC=1
      - LOG_LEVEL=debug
      - JSON_LOGGING=false
      - PROF_LISTEN_ADDRESS=0.0.0.0:9999
      - GRPC_REFLECTION=true
    ports:
      - "9999:9999"
