// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.1
// source: echo.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Echo_StreamStream_FullMethodName = "/examples.v1.Echo/StreamStream"
	Echo_StreamUnary_FullMethodName  = "/examples.v1.Echo/StreamUnary"
	Echo_UnaryStream_FullMethodName  = "/examples.v1.Echo/UnaryStream"
	Echo_UnaryUnary_FullMethodName   = "/examples.v1.Echo/UnaryUnary"
)

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoClient interface {
	StreamStream(ctx context.Context, opts ...grpc.CallOption) (Echo_StreamStreamClient, error)
	StreamUnary(ctx context.Context, opts ...grpc.CallOption) (Echo_StreamUnaryClient, error)
	UnaryStream(ctx context.Context, in *Request, opts ...grpc.CallOption) (Echo_UnaryStreamClient, error)
	UnaryUnary(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type echoClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoClient(cc grpc.ClientConnInterface) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) StreamStream(ctx context.Context, opts ...grpc.CallOption) (Echo_StreamStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[0], Echo_StreamStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &echoStreamStreamClient{stream}
	return x, nil
}

type Echo_StreamStreamClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type echoStreamStreamClient struct {
	grpc.ClientStream
}

func (x *echoStreamStreamClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *echoStreamStreamClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *echoClient) StreamUnary(ctx context.Context, opts ...grpc.CallOption) (Echo_StreamUnaryClient, error) {
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[1], Echo_StreamUnary_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &echoStreamUnaryClient{stream}
	return x, nil
}

type Echo_StreamUnaryClient interface {
	Send(*Request) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type echoStreamUnaryClient struct {
	grpc.ClientStream
}

func (x *echoStreamUnaryClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *echoStreamUnaryClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *echoClient) UnaryStream(ctx context.Context, in *Request, opts ...grpc.CallOption) (Echo_UnaryStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[2], Echo_UnaryStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &echoUnaryStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Echo_UnaryStreamClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type echoUnaryStreamClient struct {
	grpc.ClientStream
}

func (x *echoUnaryStreamClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *echoClient) UnaryUnary(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Echo_UnaryUnary_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoServer is the server API for Echo service.
// All implementations must embed UnimplementedEchoServer
// for forward compatibility
type EchoServer interface {
	StreamStream(Echo_StreamStreamServer) error
	StreamUnary(Echo_StreamUnaryServer) error
	UnaryStream(*Request, Echo_UnaryStreamServer) error
	UnaryUnary(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedEchoServer()
}

// UnimplementedEchoServer must be embedded to have forward compatible implementations.
type UnimplementedEchoServer struct {
}

func (UnimplementedEchoServer) StreamStream(Echo_StreamStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamStream not implemented")
}
func (UnimplementedEchoServer) StreamUnary(Echo_StreamUnaryServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamUnary not implemented")
}
func (UnimplementedEchoServer) UnaryStream(*Request, Echo_UnaryStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method UnaryStream not implemented")
}
func (UnimplementedEchoServer) UnaryUnary(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryUnary not implemented")
}
func (UnimplementedEchoServer) mustEmbedUnimplementedEchoServer() {}

// UnsafeEchoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServer will
// result in compilation errors.
type UnsafeEchoServer interface {
	mustEmbedUnimplementedEchoServer()
}

func RegisterEchoServer(s grpc.ServiceRegistrar, srv EchoServer) {
	s.RegisterService(&Echo_ServiceDesc, srv)
}

func _Echo_StreamStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).StreamStream(&echoStreamStreamServer{stream})
}

type Echo_StreamStreamServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type echoStreamStreamServer struct {
	grpc.ServerStream
}

func (x *echoStreamStreamServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *echoStreamStreamServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Echo_StreamUnary_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).StreamUnary(&echoStreamUnaryServer{stream})
}

type Echo_StreamUnaryServer interface {
	SendAndClose(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type echoStreamUnaryServer struct {
	grpc.ServerStream
}

func (x *echoStreamUnaryServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *echoStreamUnaryServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Echo_UnaryStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServer).UnaryStream(m, &echoUnaryStreamServer{stream})
}

type Echo_UnaryStreamServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type echoUnaryStreamServer struct {
	grpc.ServerStream
}

func (x *echoUnaryStreamServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _Echo_UnaryUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).UnaryUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_UnaryUnary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).UnaryUnary(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Echo_ServiceDesc is the grpc.ServiceDesc for Echo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Echo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "examples.v1.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryUnary",
			Handler:    _Echo_UnaryUnary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStream",
			Handler:       _Echo_StreamStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamUnary",
			Handler:       _Echo_StreamUnary_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UnaryStream",
			Handler:       _Echo_UnaryStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "echo.proto",
}
