FROM golang:1.26.1

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@v1.26.0

COPY Makefile go.mod go.sum ./
RUN make download

COPY . .
RUN DEBUG=1 make build

ENTRYPOINT ["dlv", "--listen=:2345", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "./dist/templatesrv"]
